<a href="https://colab.research.google.com/github/sharmer156/practicalAI/blob/master/notebooks_%E7%BB%83%E4%B9%A0/02_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/logo.png" width=150>

In this lesson we will learn the basics of numerical analysis using the NumPy package.

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/numpy.png" width=300>




# NumPy basics

In [0]:
import numpy as np

In [0]:
# Set seed for reproducibility
np.random.seed(seed=1234)

In [3]:
# Scalars
x = np.array(6) # scalar
print ("x: ", x)
# Number of dimensions
print ("x ndim: ", x.ndim)
# Dimensions
print ("x shape:", x.shape)
# Size of elements
print ("x size: ", x.size)
# Data type
print ("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [5]:
# 1-D Array
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

print (type(x))

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64
<class 'numpy.ndarray'>


In [6]:
# 2-D Array
x = np.array([[1.3 , 2.2 , 1.7],[1.3 , 2.2 , 1.7]])
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

print (type(x))

x:  [[1.3 2.2 1.7]
 [1.3 2.2 1.7]]
x ndim:  2
x shape: (2, 3)
x size:  6
x dtype:  float64
<class 'numpy.ndarray'>


In [7]:
# 3-D array (matrix)
x = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
x ndim:  3
x shape: (1, 3, 3)
x size:  9
x dtype:  int64


In [8]:
# Functions
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2)))
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


In [9]:
print ("np.ones((3,2)):\n", np.ones((3,2)))
print ("np.eye((4)):\n", np.eye((4)))

np.ones((3,2)):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
np.eye((4)):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Indexing 索引

In [10]:
# Indexing
x = np.array([1, 2, 3])
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x[0]:  1
x:  [0 2 3]


In [15]:
# Slicing 剖切 
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1]) 
print ("x row 0: ", x[0, :]) 
print ("x rows 0,1,2 & cols 1,2: \n", x[:3, 1:3]) 
print ("x dtype: ", x.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1,2 & cols 1,2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]
x dtype:  int64


In [19]:
# Integer array indexing 整数数组索引
print (x)
rows_to_get = np.arange(len(x))
print(len(x))
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
print ("indexed values: ", x[rows_to_get, cols_to_get])
print ("rows_to_get dtype: ", rows_to_get.dtype)
print (cols_to_get)
print ("cols_to_get: ", cols_to_get.dtype)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]
rows_to_get dtype:  int64
[0 2 1]
cols_to_get:  int64


In [20]:
# Boolean array indexing
x = np.array([[1,2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)
print ("x[x > 2]:\n", x[x > 2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# Array math 阵列数学

In [0]:
# Basic math基本运算
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/matrix.png" width=400>

# 应用





向量内积是人工智能领域中的神经网络技术的数学基础之一。

此方法被用于动画渲染（Animation-Rendering）。

*   物理学中力学的力做功的问题，经常用到点积计算。
*  计算机图形学常用进行方向性判断，如两向量点积大于0，则它们的方向朝向相近；如小于0，则方向相反。
*  向量内积是人工智能领域中的神经网络技术的数学基础之一。
* 此方法被用于动画渲染（Animation-Rendering）。

广义定义
在一个向量空间V中，定義在 V*V上的正定对称双线性形式函數即是V的內積，而添加有一个数量积的向量空间即是内积空间


In [22]:
# Dot product 点积 https://zh.wikipedia.org/wiki/%E7%82%B9%E7%A7%AF

a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
print (a.dot(b))

[[ 58.  64.]
 [139. 154.]]


In [23]:
# Sum across a dimension 维度和
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum by col: ", np.sum(x, axis=0)) # add numbers in each column
print ("sum by row: ", np.sum(x, axis=1)) # add numbers in each row

[[1 2]
 [3 4]]
sum all:  10
sum by col:  [4 6]
sum by row:  [3 7]


In [24]:
# Transposing 矩阵转置，类似表格中的横纵行调换
print ("x:\n", x)
print ("x.T:\n", x.T)

x:
 [[1 2]
 [3 4]]
x.T:
 [[1 3]
 [2 4]]


# Advanced

In [25]:
# Tile 覆盖
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])
addent = np.tile(y, (len(x), 1))
print ("addent: \n", addent)
z = x + addent
print ("z:\n", z)

addent: 
 [[5 6]
 [5 6]]
z:
 [[ 6  8]
 [ 8 10]]


In [0]:
# Broadcasting
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])
z = x + y
print ("z:\n", z)

z:
 [[ 6  8]
 [ 8 10]]


In [0]:
# Reshaping
x = np.array([[1,2], [3,4], [5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y.shape: ", y.shape)
print ("y: \n", y)

[[1 2]
 [3 4]
 [5 6]]
x.shape:  (3, 2)
y.shape:  (2, 3)
y: 
 [[1 2 3]
 [4 5 6]]


In [0]:
# Removing dimensions降维
x = np.array([[[1,2,1]],[[2,2,3]]])
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # squeeze dim 1
print ("y.shape: ", y.shape) 
print ("y: \n", y)

x.shape:  (2, 1, 3)
y.shape:  (2, 3)
y: 
 [[1 2 1]
 [2 2 3]]


In [38]:
x = np.array([[[[1,2,1]]],[[[2,2,3]]],[[[2,2,3]]]])
y = np.squeeze(x, 1)

print ("x: \n", x)

print ("x.shape: ", x.shape)
print ("y.shape: ", y.shape) 
print ("我们世界的维度: ", x.ndim)
print ("被二向箔攻击后的维度: ", y.ndim)

print ("y: \n", y)

print('x.dtype',x.dtype)
print('y.dtype',y.dtype)

x: 
 [[[[1 2 1]]]


 [[[2 2 3]]]


 [[[2 2 3]]]]
x.shape:  (3, 1, 1, 3)
y.shape:  (3, 1, 3)
我们世界的维度:  4
被二向箔攻击后的维度:  3
y: 
 [[[1 2 1]]

 [[2 2 3]]

 [[2 2 3]]]
x.dtype int64
y.dtype int64


In [0]:
# Adding dimensions
x = np.array([[1,2,1],[2,2,3]])
print ("x.shape: ", x.shape)
y = np.expand_dims(x, 1) # expand dim 1
print ("y.shape: ", y.shape) 
print ("y: \n", y)

x.shape:  (2, 3)
y.shape:  (2, 1, 3)
y: 
 [[[1 2 1]]

 [[2 2 3]]]


# Additional resources

You don't have to memorize anything here and we will be taking a closer look at NumPy in the later lessons. If you are curious about more checkout the [NumPy reference manual](https://docs.scipy.org/doc/numpy-1.15.1/reference/).